import os
import requests
import sys

def project():
    v_rep = os.getcwd()
    v_rep+= "\\" + input("Name of the project to create or update: ") + "\\"
    
    try:
        os.mkdir(v_rep)
    except OSError:
        raise OSError("error")
    # .gitignore
    v_gitignore = "https://www.gitignore.io/api/python"
    v_response = requests.get(v_gitignore)
    if v_response.status_code == 200:
        with open(v_rep + ".gitignore", "w+") as v_target:
            v_target.write(v_response.text)
    else:
        raise requests.RequestException(f'.gitignore <response {v_response.status_code}>')
    # others files
    v_gen = ["LICENCE", "requirements.txt", "setup.py"]
    for v_tmp in v_gen:
        with open(v_rep + v_tmp, "w"): pass
    # README.md 
    with open(v_rep + "README.md", "w") as v_target: 
        v_target.write(f"""# Generated by Lyppy
> A project developed by norro valentin
* Lyppy : https://github.com/norrova/Lyppy"
* .gitignore : {v_gitignore}""")

def module():
    v_rep = os.getcwd()
    v_name = input("Name of the module to create or update: ")
    v_rep+= "\\" + v_name + "\\"
    try:
        if not os.path.exists(v_rep):
            os.mkdir(v_rep)
    except OSError:
        raise OSError("error")
    with open(v_rep + "__init__.py","w"): pass
    with open(v_rep + v_name + ".py","w") as v_target:
        v_target.write(
"""def main():
    raise NotImplementedError()

if __name__ == "__main__":
    main()""")

def remove():
    print("remove")
    return 0